import React, { useEffect, useMemo, useState } from 'react'
import {
  LayoutDashboard, BookOpen, Brain, ListChecks, BarChart3, Trophy, Users,
  Bell, Sparkles, GraduationCap, PlayCircle, CheckCircle2, Clock3, Flame,
  Target, MessageCircle, Search, Megaphone, Zap, CalendarDays, ChevronRight,
  ShieldCheck, Bot, UserRoundCheck, CircleAlert, Send, Settings2, FileText
} from 'lucide-react'
import { supabase } from './supabase'

const fallback = {
  student:{full_name:'Omar Mohamed',points:1280,streak:12},
  teacher:{full_name:'Dr. Ahmed Hassan'},
  course:{title:'Biology Mastery 2027',subject:'Biology',instructor_name:'Dr. Ahmed Hassan'},
  lessons:[
    {id:'l1',title:'Cell Structure & Function',summary:'Understand organelles and how cell structure supports function.',duration_minutes:42,position:1},
    {id:'l2',title:'DNA & Gene Expression',summary:'From DNA structure to transcription and translation.',duration_minutes:55,position:2},
    {id:'l3',title:'Human Physiology',summary:'Circulation, respiration and homeostasis.',duration_minutes:48,position:3}
  ],
  plan:[
    {task:'Review DNA transcription',day:'Today',minutes:25},
    {task:'Complete DNA Challenge quiz',day:'Today',minutes:15},
    {task:'Watch Human Physiology lesson',day:'Tomorrow',minutes:48},
    {task:'Revise weak topic: protein synthesis',day:'Tomorrow',minutes:20}
  ]
}

const students = [
  {name:'Omar Mohamed',progress:68,score:86,status:'Active',last:'2h ago',risk:18,trend:'+6%',weak:'DNA transcription',reason:'Healthy engagement',recommended:'Keep current plan'},
  {name:'Sara Ali',progress:82,score:91,status:'Active',last:'35m ago',risk:8,trend:'+9%',weak:'Genetics',reason:'High engagement',recommended:'Advanced quiz'},
  {name:'Youssef Karim',progress:41,score:59,status:'At risk',last:'6d ago',risk:87,trend:'-14%',weak:'DNA & protein synthesis',reason:'6 days inactive · 3 low scores',recommended:'Send reminder + revision plan'},
  {name:'Mariam Ahmed',progress:74,score:84,status:'Active',last:'1d ago',risk:22,trend:'+3%',weak:'Human physiology',reason:'Stable performance',recommended:'Continue plan'},
  {name:'Adham Tarek',progress:37,score:62,status:'At risk',last:'8d ago',risk:92,trend:'-18%',weak:'Cell biology',reason:'8 days inactive · progress stalled',recommended:'Urgent teacher follow-up'},
  {name:'Laila Samir',progress:53,score:66,status:'Watch',last:'3d ago',risk:61,trend:'-7%',weak:'Genetics',reason:'Quiz accuracy declining',recommended:'Targeted 20-min revision'}
]

const nav = [
  ['dashboard','Dashboard',LayoutDashboard],['courses','Courses',BookOpen],['tutor','AI Tutor',Brain],
  ['quizzes','Quizzes',ListChecks],['analytics','Analytics',BarChart3],['achievements','Achievements',Trophy]
]
const teacherNav = [
  ['dashboard','Overview',LayoutDashboard],['students','Students',Users],['content','Content',BookOpen],
  ['analytics','Analytics',BarChart3],['automation','Automation',Zap],['announcements','Announcements',Megaphone]
]

function Card({children,className=''}){return <div className={'card '+className}>{children}</div>}
function SectionHead({eyebrow,title,icon:Icon}){return <div className="section-head"><div><small>{eyebrow}</small><h2>{title}</h2></div>{Icon&&<Icon/>}</div>}
function Stat({icon:Icon,value,label,sub}){return <Card className="stat"><div className="iconbox"><Icon size={20}/></div><div><strong>{value}</strong><span>{label}</span>{sub&&<em>{sub}</em>}</div></Card>}
function Progress({value}){return <div className="progress"><i style={{width:`${value}%`}}/></div>}
function Badge({children,type=''}){return <span className={'badge '+type}>{children}</span>}

function StudentDashboard({data,setPage}){
  return <>
    <section className="hero"><div><div className="eyebrow"><Sparkles size={16}/> Personalized learning dashboard</div><h1>Welcome back, {data.student.full_name.split(' ')[0]} 👋</h1><p>Your AI study plan adapts to your weak topics and recent quiz results.</p></div><div className="hero-badge"><Flame/><div><b>{data.student.streak} days</b><span>Study streak</span></div></div></section>
    <div className="stats"><Stat icon={Target} value="68%" label="Course progress" sub="+8% this week"/><Stat icon={Trophy} value={data.student.points} label="XP points" sub="Top 18%"/><Stat icon={CheckCircle2} value="86%" label="Quiz average" sub="+4% vs last week"/><Stat icon={Clock3} value="3h 10m" label="This week" sub="Goal: 4h"/></div>
    <div className="grid two"><Card><SectionHead eyebrow="Continue learning" title={data.course.title} icon={BookOpen}/><Progress value={68}/><p className="muted">68% complete · 3 lessons in this demo</p><div className="lesson-list">{data.lessons.map((l,i)=><button className="lesson" key={l.id} onClick={()=>setPage('courses')}><div className="lesson-num">{i+1}</div><div className="grow"><b>{l.title}</b><span>{l.summary}</span></div><span className="duration">{l.duration_minutes} min</span><PlayCircle size={20}/></button>)}</div></Card>
    <Card><SectionHead eyebrow="AI generated" title="Today's study plan" icon={ListChecks}/>{data.plan.map((t,i)=><div className="task" key={i}><div><b>{t.task}</b><span>{t.day} · {t.minutes} min</span></div><CheckCircle2 size={20}/></div>)}</Card></div>
    <div className="grid three"><Card><SectionHead eyebrow="Weak topic" title="DNA transcription" icon={CircleAlert}/><p className="muted">You missed 3 of the last 5 questions on transcription.</p><button className="primary" onClick={()=>setPage('tutor')}>Ask AI Tutor</button></Card><Card><SectionHead eyebrow="Next milestone" title="Quiz Master" icon={Trophy}/><p className="muted">Score 90%+ in two more quizzes to unlock 500 XP.</p><Progress value={67}/></Card><Card><SectionHead eyebrow="Upcoming" title="Weekly biology challenge" icon={CalendarDays}/><p className="muted">Saturday · 8:00 PM · 20 questions</p><Badge type="blue">Starts in 2 days</Badge></Card></div>
  </>
}

function Courses({data}){return <><PageTitle title="Courses" text="All lessons, progress and learning resources in one place."/><div className="course-banner"><div><Badge type="blue">{data.course.subject}</Badge><h2>{data.course.title}</h2><p>Instructor: {data.course.instructor_name}</p><Progress value={68}/></div><div className="course-score"><b>68%</b><span>completed</span></div></div><div className="lesson-list large">{data.lessons.map((l,i)=><Card className="lesson-card" key={l.id}><div className="lesson-num">{i+1}</div><div className="grow"><b>{l.title}</b><p>{l.summary}</p><span><Clock3 size={14}/> {l.duration_minutes} minutes</span></div><button className="primary"><PlayCircle size={17}/> Start lesson</button></Card>)}</div></>}

function Tutor(){const [messages,setMessages]=useState([{role:'ai',text:'Hi Omar! Ask me anything from your Biology course. I can explain concepts, quiz you, or simplify a difficult topic.'}]);const [q,setQ]=useState('');function send(e){e.preventDefault();if(!q.trim())return;const a=q.toLowerCase().includes('mitochond')?'Mitochondria convert energy from nutrients into ATP through cellular respiration. In exams, remember: inner membrane → electron transport chain → ATP production.':'Here is the exam-focused version: break the concept into definition, mechanism, and one clinical/example link. For this demo, I use the current course context and your weak-topic profile.';setMessages(m=>[...m,{role:'user',text:q},{role:'ai',text:a}]);setQ('')}
return <><PageTitle title="AI Tutor" text="Context-aware help based on the current course and your learning gaps."/><Card className="tutor-shell"><div className="tutor-top"><div className="avatar"><Brain/></div><div><b>CourseAI Tutor</b><span>Biology Mastery 2027 · Online</span></div><Badge type="green">Course-aware</Badge></div><div className="messages">{messages.map((m,i)=><div key={i} className={'message '+m.role}>{m.text}</div>)}</div><form className="ask" onSubmit={send}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ask a biology question..."/><button><Send size={17}/> Send</button></form><div className="chips">{['Explain transcription simply','Quiz me on cells','Make a 20-min revision plan'].map(x=><button key={x} onClick={()=>setQ(x)}>{x}</button>)}</div></Card></>}

function Quizzes(){const [started,setStarted]=useState(false);const [answer,setAnswer]=useState('');const [result,setResult]=useState(null);return <><PageTitle title="Quizzes" text="Adaptive checkpoints that feed your weak-topic analysis."/><div className="grid two"><Card><SectionHead eyebrow="Recommended" title="DNA Challenge" icon={Target}/><p className="muted">10 questions · Hard · AI recommends this because DNA is your weakest topic.</p>{!started?<button className="primary" onClick={()=>setStarted(true)}>Start adaptive quiz</button>:<><p className="question">Which organelle is primarily responsible for ATP production?</p>{['Nucleus','Mitochondrion','Ribosome','Golgi apparatus'].map(o=><label className={'option '+(answer===o?'selected':'')} key={o}><input type="radio" name="q" value={o} onChange={e=>setAnswer(e.target.value)}/>{o}</label>)}<button className="primary" onClick={()=>setResult(answer==='Mitochondrion')}>Check answer</button>{result!==null&&<div className={'feedback '+(result?'good':'bad')}>{result?'Correct. Mitochondria generate most cellular ATP.':'Try again. Focus on cellular respiration.'}</div>}</>}</Card><Card><SectionHead eyebrow="Performance" title="Recent attempts" icon={BarChart3}/>{[['Cell Biology Checkpoint',92,'Excellent'],['DNA Basics',71,'Needs review'],['Human Physiology',85,'Good']].map(r=><div className="result-row" key={r[0]}><div><b>{r[0]}</b><span>{r[2]}</span></div><strong>{r[1]}%</strong></div>)}</Card></div></>}

function StudentAnalytics(){return <><PageTitle title="Analytics" text="Your learning patterns, strengths and weak topics."/><div className="stats"><Stat icon={BarChart3} value="+12%" label="Progress growth"/><Stat icon={Target} value="86%" label="Accuracy"/><Stat icon={Clock3} value="6.4h" label="Study time / 30d"/><Stat icon={Flame} value="12" label="Current streak"/></div><div className="grid two"><Card><SectionHead eyebrow="Topic mastery" title="Where you stand" icon={Target}/>{[['Cell structure',91],['Human physiology',82],['DNA transcription',63],['Protein synthesis',69]].map(([n,v])=><div className="bar-row" key={n}><span>{n}</span><Progress value={v}/><b>{v}%</b></div>)}</Card><Card><SectionHead eyebrow="AI insight" title="Best next action" icon={Brain}/><div className="insight"><Sparkles/><div><b>Spend 25 minutes on DNA transcription today.</b><p>You are likely to gain the most score improvement by reviewing transcription before taking another hard quiz.</p></div></div><div className="insight"><Clock3/><div><b>Your best study window is 7–9 PM.</b><p>Your recent completion rate is highest during this period.</p></div></div></Card></div></>}

function Achievements(){return <><PageTitle title="Achievements" text="Streaks, XP and milestones designed to keep momentum high."/><div className="achievement-grid">{[['🔥','12 Day Streak','Study 12 days in a row','Unlocked'],['🏆','Quiz Master','Score 90%+ on 3 quizzes','2 / 3'],['🚀','Fast Starter','Complete your first module','Unlocked'],['🧠','DNA Specialist','Reach 85% mastery in DNA','63%'],['⭐','Top 10%','Reach top 10% of cohort','18%']].map(a=><Card key={a[1]} className="achievement"><div className="emoji">{a[0]}</div><b>{a[1]}</b><p>{a[2]}</p><Badge type={a[3]==='Unlocked'?'green':'blue'}>{a[3]}</Badge></Card>)}</div></>}

function TeacherDashboard(){
  const [action,setAction]=useState('')
  const riskStudents=students.filter(s=>s.risk>=60).sort((a,b)=>b.risk-a.risk)
  function runAction(student,type){setAction(`${type} prepared for ${student.name}`);setTimeout(()=>setAction(''),2800)}
  return <>
    <section className="hero teacher-hero"><div><div className="eyebrow"><Brain size={16}/> AI teacher command center</div><h1>Biology Mastery 2027</h1><p>Prioritize who needs help, why they are struggling, and what action to take next.</p></div><div className="hero-badge"><Bell/><div><b>{riskStudents.length} priority students</b><span>AI risk queue</span></div></div></section>
    {action&&<div className="toast"><CheckCircle2 size={18}/>{action}</div>}
    <div className="stats"><Stat icon={Users} value="128" label="Students" sub="+14 this month"/><Stat icon={BarChart3} value="74%" label="Avg. progress" sub="+6%"/><Stat icon={Target} value="81%" label="Avg. quiz score" sub="+3%"/><Stat icon={Bell} value="9" label="Need attention" sub="3 high priority"/></div>
    <div className="grid teacher-main-grid">
      <Card><SectionHead eyebrow="Priority queue" title="At-risk students" icon={CircleAlert}/><div className="risk-list">{riskStudents.map(s=><div className="risk-card" key={s.name}><div className="risk-score"><strong>{s.risk}</strong><span>risk</span></div><div className="grow"><div className="risk-title"><b>{s.name}</b><Badge type={s.risk>=80?'red':'blue'}>{s.risk>=80?'High risk':'Watch'}</Badge></div><p>{s.reason}</p><div className="risk-meta"><span>Weak: {s.weak}</span><span>Last active: {s.last}</span><span className="down">Trend {s.trend}</span></div><div className="suggestion"><Sparkles size={15}/><span><b>AI suggestion:</b> {s.recommended}</span></div><div className="risk-actions"><button className="primary small" onClick={()=>runAction(s,'Reminder')}><Send size={15}/> Prepare reminder</button><button className="secondary small" onClick={()=>runAction(s,'Revision plan')}><Brain size={15}/> AI study plan</button></div></div></div>)}</div></Card>
      <div className="stack"><Card><SectionHead eyebrow="AI insights" title="What changed this week" icon={Brain}/><TeacherInsights/></Card><Card><SectionHead eyebrow="Cohort health" title="Risk distribution" icon={ShieldCheck}/><div className="health-row"><div><strong>79%</strong><span>On track</span></div><div><strong>14%</strong><span>Watch</span></div><div><strong>7%</strong><span>High risk</span></div></div><Progress value={79}/><p className="muted">Most risk is driven by inactivity and repeated low quiz scores.</p></Card></div>
    </div>
    <div className="grid two"><Card><SectionHead eyebrow="Lesson performance" title="Mastery by topic" icon={BarChart3}/>{[['Cell Structure & Function',88],['DNA & Gene Expression',63],['Human Physiology',79],['Genetics',71]].map(([n,v])=><div className="bar-row" key={n}><span>{n}</span><Progress value={v}/><b>{v}%</b></div>)}</Card><Card><SectionHead eyebrow="Automation preview" title="Recommended teacher actions" icon={Zap}/>{[['Send inactivity reminders','5 students','Ready'],['Generate DNA revision plans','12 students','Suggested'],['Celebrate high performers','18 students','Ready']].map(x=><div className="result-row" key={x[0]}><div><b>{x[0]}</b><span>{x[1]}</span></div><Badge type="blue">{x[2]}</Badge></div>)}</Card></div>
    <StudentTable compact/>
  </>
}
function TeacherInsights(){return <>{[['DNA & Gene Expression is the weakest topic','37% of students missed transcription/translation questions.'],['9 students are at risk of dropping behind','Low activity or declining quiz performance detected.'],['Engagement is up 18%','Streaks and weekly challenges are improving return visits.']].map((x,i)=><div className="insight" key={x[0]}>{i===0?<CircleAlert/>:i===1?<Bell/>:<Trophy/>}<div><b>{x[0]}</b><p>{x[1]}</p></div></div>)}</>}
function StudentTable({compact=false}){
  const [selected,setSelected]=useState(null)
  const rows=compact?students.slice(0,5):students
  return <Card><SectionHead eyebrow="Student intelligence" title={compact?'Student performance':'All students'} icon={Users}/><div className="table-wrap"><table><thead><tr><th>Student</th><th>Progress</th><th>Quiz avg.</th><th>Risk</th><th>Last active</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(s=><tr key={s.name} className="click-row" onClick={()=>setSelected(s)}><td><b>{s.name}</b></td><td>{s.progress}%</td><td>{s.score}%</td><td><span className={'risk-number '+(s.risk>=80?'danger':s.risk>=60?'warn':'safe')}>{s.risk}</span></td><td>{s.last}</td><td><Badge type={s.status==='At risk'?'red':s.status==='Watch'?'blue':'green'}>{s.status}</Badge></td><td><ChevronRight size={18}/></td></tr>)}</tbody></table></div>{selected&&<div className="student-detail"><div className="detail-head"><div><small>STUDENT PROFILE</small><h3>{selected.name}</h3></div><button className="icon-btn" onClick={()=>setSelected(null)}>×</button></div><div className="detail-stats"><div><b>{selected.progress}%</b><span>Progress</span></div><div><b>{selected.score}%</b><span>Quiz avg.</span></div><div><b>{selected.risk}</b><span>Risk score</span></div><div><b>{selected.trend}</b><span>Trend</span></div></div><div className="detail-note"><CircleAlert size={17}/><div><b>Why flagged</b><p>{selected.reason}</p></div></div><div className="detail-note"><Brain size={17}/><div><b>Recommended action</b><p>{selected.recommended}</p></div></div></div>}</Card>
}
function TeacherStudents(){
  const [query,setQuery]=useState('');const [filter,setFilter]=useState('All')
  const filtered=students.filter(s=>s.name.toLowerCase().includes(query.toLowerCase())&&(filter==='All'||s.status===filter))
  return <><PageTitle title="Students" text="Search students, identify risk and inspect performance."/><div className="toolbar"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search student..."/></div><div className="filter-pills">{['All','At risk','Watch','Active'].map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div><button className="secondary"><UserRoundCheck size={17}/> Add student</button></div><div className="stats mini-stats"><Stat icon={CircleAlert} value="9" label="Need attention"/><Stat icon={Clock3} value="5" label="Inactive 5+ days"/><Stat icon={Target} value="12" label="Score below 65%"/><Stat icon={Brain} value="17" label="AI plans ready"/></div><StudentTableCustom rows={filtered}/></>
}
function StudentTableCustom({rows}){const [selected,setSelected]=useState(null);return <Card><div className="table-wrap"><table><thead><tr><th>Student</th><th>Progress</th><th>Quiz avg.</th><th>Risk</th><th>Weak topic</th><th>Last active</th><th>Status</th></tr></thead><tbody>{rows.map(s=><tr key={s.name} className="click-row" onClick={()=>setSelected(s)}><td><b>{s.name}</b></td><td><div className="inline-progress"><Progress value={s.progress}/><span>{s.progress}%</span></div></td><td>{s.score}%</td><td><span className={'risk-number '+(s.risk>=80?'danger':s.risk>=60?'warn':'safe')}>{s.risk}</span></td><td>{s.weak}</td><td>{s.last}</td><td><Badge type={s.status==='At risk'?'red':s.status==='Watch'?'blue':'green'}>{s.status}</Badge></td></tr>)}</tbody></table></div>{selected&&<div className="student-detail"><div className="detail-head"><div><small>AI RISK REVIEW</small><h3>{selected.name}</h3></div><button className="icon-btn" onClick={()=>setSelected(null)}>×</button></div><div className="detail-note"><CircleAlert size={17}/><div><b>Detected issue</b><p>{selected.reason}</p></div></div><div className="detail-note"><Brain size={17}/><div><b>Suggested intervention</b><p>{selected.recommended}</p></div></div><div className="risk-actions"><button className="primary small"><Send size={15}/> Prepare message</button><button className="secondary small"><ListChecks size={15}/> Generate plan</button></div></div>}</Card>}
function TeacherContent({data}){return <><PageTitle title="Content" text="Course modules, lessons, quizzes and resources."/><div className="toolbar"><span>{data.lessons.length} lessons</span><button className="primary"><BookOpen size={17}/> New lesson</button></div><div className="lesson-list large">{data.lessons.map((l,i)=><Card className="lesson-card" key={l.id}><div className="lesson-num">{i+1}</div><div className="grow"><b>{l.title}</b><p>{l.summary}</p><span><Clock3 size={14}/> {l.duration_minutes} min · Published</span></div><Badge type="green">Live</Badge><button className="icon-btn"><Settings2/></button></Card>)}</div></>}
function TeacherAnalytics(){return <><PageTitle title="Analytics" text="Cohort performance and AI-generated teaching insights."/><div className="stats"><Stat icon={Users} value="128" label="Students"/><Stat icon={Target} value="81%" label="Avg score"/><Stat icon={Clock3} value="4.2h" label="Avg weekly study"/><Stat icon={Flame} value="67%" label="Weekly active"/></div><div className="grid two"><Card><SectionHead eyebrow="Performance" title="Topic mastery" icon={BarChart3}/>{[['Cells',88],['DNA',63],['Physiology',79],['Genetics',71]].map(([n,v])=><div className="bar-row" key={n}><span>{n}</span><Progress value={v}/><b>{v}%</b></div>)}</Card><Card><SectionHead eyebrow="AI commentary" title="This week" icon={Brain}/><TeacherInsights/></Card></div></>}
function Automation(){const [toggles,setToggles]=useState({risk:true,inactive:true,quiz:true,weekly:true});const items=[['risk','At-risk student alert','Notify teacher when engagement or scores drop.',Bell],['inactive','Inactive student follow-up','Prepare a reminder after 5 days of inactivity.',MessageCircle],['quiz','Low-score revision plan','Generate a revision plan when score is below 65%.',Brain],['weekly','Weekly teacher report','Summarize growth, weak topics and students needing attention.',FileText]];return <><PageTitle title="Automation Center" text="Demo automation rules ready to be connected to n8n / WhatsApp / email."/><Card><div className="automation-list">{items.map(([k,t,d,Icon])=><div className="automation-row" key={k}><div className="iconbox"><Icon/></div><div className="grow"><b>{t}</b><span>{d}</span></div><button className={'toggle '+(toggles[k]?'on':'')} onClick={()=>setToggles(x=>({...x,[k]:!x[k]}))}><i/></button></div>)}</div></Card><div className="grid two"><Card><SectionHead eyebrow="Demo workflow" title="At-risk follow-up" icon={Zap}/><div className="flow"><span>Student inactive</span><ChevronRight/><span>AI risk check</span><ChevronRight/><span>Teacher alert</span></div></Card><Card><SectionHead eyebrow="Integration status" title="Ready for automation layer" icon={ShieldCheck}/><p className="muted">Database events and demo rules are structured. n8n can be connected later without changing the UI architecture.</p><Badge type="blue">Demo-ready</Badge></Card></div></>}
function Announcements(){const [text,setText]=useState('');const [sent,setSent]=useState(false);return <><PageTitle title="Announcements" text="Send updates, revision reminders and challenge notices."/><div className="grid two"><Card><SectionHead eyebrow="Compose" title="New announcement" icon={Megaphone}/><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Example: DNA revision session tomorrow at 8 PM..."/><button className="primary" onClick={()=>{if(text.trim())setSent(true)}}><Send size={17}/> Send demo announcement</button>{sent&&<div className="feedback good">Demo announcement queued successfully.</div>}</Card><Card><SectionHead eyebrow="Recent" title="Latest messages" icon={MessageCircle}/>{[['Weekly challenge','Saturday · 8:00 PM'],['DNA revision reminder','Yesterday'],['New lesson published','3 days ago']].map(x=><div className="result-row" key={x[0]}><div><b>{x[0]}</b><span>{x[1]}</span></div><CheckCircle2/></div>)}</Card></div></>}
function PageTitle({title,text}){return <div className="page-title"><div><h1>{title}</h1><p>{text}</p></div></div>}

export default function App(){
  const [mode,setMode]=useState('student');const [page,setPage]=useState('dashboard');const [data,setData]=useState(fallback);const [loading,setLoading]=useState(true)
  useEffect(()=>{(async()=>{try{const [{data:profiles},{data:courses},{data:lessons},{data:plans}]=await Promise.all([supabase.from('profiles').select('*'),supabase.from('courses').select('*').limit(1),supabase.from('lessons').select('*').order('position'),supabase.from('study_plans').select('*').limit(1)]);setData({student:profiles?.find(p=>p.role==='student')||fallback.student,teacher:profiles?.find(p=>p.role==='teacher')||fallback.teacher,course:courses?.[0]||fallback.course,lessons:lessons?.length?lessons:fallback.lessons,plan:plans?.[0]?.tasks||fallback.plan})}catch(e){console.warn(e)}setLoading(false)})()},[])
  const menu=mode==='student'?nav:teacherNav
  function render(){if(mode==='student'){return page==='dashboard'?<StudentDashboard data={data} setPage={setPage}/>:page==='courses'?<Courses data={data}/>:page==='tutor'?<Tutor/>:page==='quizzes'?<Quizzes/>:page==='analytics'?<StudentAnalytics/>:<Achievements/>}return page==='dashboard'?<TeacherDashboard/>:page==='students'?<TeacherStudents/>:page==='content'?<TeacherContent data={data}/>:page==='analytics'?<TeacherAnalytics/>:page==='automation'?<Automation/>:<Announcements/>}
  return <div className="app"><aside><div className="brand"><div className="logo"><GraduationCap/></div><div><b>CourseAI</b><span>Learning OS</span></div></div><nav>{menu.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon/>{label}</button>)}</nav><div className="demo-note"><Sparkles/><div><b>Interactive demo</b><span>Supabase-connected prototype</span></div></div></aside><main><header><div><b>Biology Academy</b><span>{loading?'Syncing demo data...':'Live demo data connected'}</span></div><div className="header-actions"><Bell size={18}/><div className="mode-switch"><button className={mode==='student'?'on':''} onClick={()=>{setMode('student');setPage('dashboard')}}>Student</button><button className={mode==='teacher'?'on':''} onClick={()=>{setMode('teacher');setPage('dashboard')}}>Teacher</button></div></div></header><div className="content">{render()}</div></main></div>
}
